spring:
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins:
                            -   'http://localhost:3000'
                        allowedMethods: '*'
                        allowedHeaders: '*'
                        exposedHeaders: '*'
                        allowCredentials: true
            routes:
                -   id: user-service
                    predicates: 
                        -   Path=/user-service/**
                    filters:
                        -   StripPrefix=1
                    uri: lb://user-service

                -   id: product-service
                    predicates: 
                        -   Path=/product-service/**
                    filters:
                        -   StripPrefix=1
                    uri: lb://product-service
                -   id: order-service
                    predicates: 
                        -   Path=/order-service/**
                    filters:
                        -   StripPrefix=1
                    uri: lb://order-service

jwt:
    secret: jslim-super-secret-key-for-jwt-123456789
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/